runtime: custom
env: flex
env_variables:
  TAP_SLACK_TOKEN: "xoxb-16733365862-1325363092995-5JWCZwU9Tr735Iwfsoo7nPtQ"
  TAP_ZOOM_JWT: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOm51bGwsImlzcyI6IlA1YVk0QjdEUW1pUHV6Tm5PZXhCNUEiLCJleHAiOjI1MjQ2MzMyMDAsImlhdCI6MTYwNDU5MDA0NX0.HWqLrM7nk6NHNrf9qhsfNwlmErdyBqUXw3siWXfs9dc"
  SF_USER: "michaelcooper"
  SF_PASSWORD: "g&HUrB8YJ;r,Q2k88"
  AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT: 120
  AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
  AIRFLOW__CORE__SQL_ALCHEMY_CONNL: "postgresql://postgres:OniFbN6Jwbucr5MI@/postgres?host=/cloudsql/gadmin-reports-294123:us-central1:gitlab"
manual_scaling:
  instances: 1
beta_settings:
  cloud_sql_instances: "gadmin-reports-294123:us-central1:gitlab"